import { setConfig } from 'common/commonClass';
import WindowPanel from 'component/windowPanel';

export default function accountForm(opt){
    var fields=[
        {
            column:[
                {
                    label:'商家名称',
                    required:true,
                    name:'name',
                    validator:{
                        type:['validateLength'],
                        validateRule:{
                            min:1,
                            max:50
                        }
                    }
                },{
                    label:'联系地址',
                    required:true,
                    name:'address',
                    validator:{
                        type:['validateLength'],
                        validateRule:{
                            min:1,
                            max:100
                        }
                    }
                }

            ],
            extraClass:{
                boxDiv:['col-sm-6']
            }
        },{
            column:[
                {
                    label:'联系人',
                    name:'contactPerson',
                    required:true,
                    validator:{
                        type:['validateLength'],
                        validateRule:{
                            min:1,
                            max:50
                        }
                    }
                },{
                    label:'联系电话',
                    name:'contactPhone',
                    required:true,
                    validator:{
                        type:['validateNumber','validateLength'],
                        validateRule:{
                            min:1,
                            max:11,
                        }
                    }
                }
            ],
            extraClass:{
                boxDiv:['col-sm-6']
            }
        },{
            column:[
                {
                    label:'营业执照',
                    name:'businessLicenseUrl',
                    required:true,
                    type:'img'
                },
                {
                    label:'是否发布',
                    name:'isRelease',
                    type:'radio',
                    option:[
                        {
                            html:'发布',
                            value:'Y'
                        },
                        {
                            html:'暂不发布',
                            value:'N'
                        }
                    ]
                }
            ],
            extraClass:{
                boxDiv:['col-sm-6']
            }
        }
    ];
    var btns={
        edit:{
            html:'确认',
            extraClass:['layui-layer-btn0'],
            events:{
                click:function(opt){
                    if(opt.panel.items['accountForm'].validatesFn({windowBtn:opt.btn})){
                        var loading = layer.load(1,{shade: [0.1,'#fff'] });
                        $.ajax({
                            url:$(opt.panel.component).find('input[name=id]').length?'/store/update':'/store/add',
                            type:'post',
                            data:$('.'+opt.panel.component.className.split(' ')[0]).find('form').serialize(),//+userType,
                            success:function(response){
                                if(response.isSuccess){
                                    layer.closeAll();
                                    layer.msg('保存成功!');
                                    opt.panel.owner.refresh();
                                }else{
                                    layer.close(loading);
                                    layer.msg(response.errorMessage,function(){});
                                }
                            },
                            error:function(response){
                                layer.close(loading);
                                layer.alert('错误代码:'+response.status+'，请联系管理员',{title:'错误提示',shadeClose: true});
                            }
                        });
                    }
                }
            }
        },
        closeBtn:{
            html:'关闭',
            extraClass:['layui-layer-btn0'],
            events:{
                click:function(opt){
                    layer.closeAll();
                }
            }
        },
        reload:{
            html:'重置',
            extraClass:['layui-layer-btn0'],
            events:{
                click:function(opt){
                    for(var i in opt.panel.items){
                        if(opt.panel.items[i].refresh)
                            opt.panel.items[i].refresh();
                    }
                }
            }
        }
    }
    return new WindowPanel({
        owner:opt.owner,
        layerConfig:{
            area:'1000px',
            title:opt.data?'编辑商家信息':'新建商家信息'
        },
        btns:btns,
        items:[
            setConfig({
                opt:opt,
                fnName:'accountForm',
                config:{
                    xtype:'FormPanel',
                    data:opt.data,
                    fields:fields,
                    queryUrl:'/store/queryById',
                    queryType:'post'
                }
            })
        ]
    });
}
